import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import ThemeProvider from "@/providers/theme-provider";
import RegionProvider from "@/providers/region-provider";

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "600", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={nunito_sans.className}>
        <ThemeProvider>
          <RegionProvider>
            <main className="min-h-screen bg-white dark:bg-dark-mode-bg">
              <Header />
              {children}
            </main>
          </RegionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
